---
title: "Rworksheet3b"
output: html_document
date: "2023-10-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

UpperLetters<- LETTERS [1:26]
UpperLetters

LowerLetters<- letters [1:26]
LowerLetters

#a.
First_11 <- LETTERS [1:11]
First_11
#b.
OddLetters <- UpperLetters [c(TRUE, FALSE)]
OddLetters
#c.
VowelLetters <- LETTERS [c(1,5,9,15,21)]
VowelLetters
#d.
LastLetters <- letters [c(22,23,24,25,26)]
LastLetters
#e.
BetLetters <- letters [15:24]
BetLetters

#2. 
#a.
city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
city
#b.
temp <- c(42,39,34,34,30,27)
temp
#c.
data <- data.frame(city, temp)
data
#d.
names(data) <- c("City", "Temperature")
data
#e.
str(df)
#The output function (x, df1, df2, ncp, 
#    log = FALSE)

#f.
data [c(3, 4),]
#data [c(3, 4),]
#         City Temperature
#3 Iloilo City          34
#4    Tacloban          34

#g.
max_temp_city <- data[which.max(data$Temperature), "City"]
min_temp_city <- data[which.min(data$Temperature), "City"]
max_temp_city
min_temp_city
#max_temp_city
#[1] "Tuguegarao City"
#> min_temp_city
#[1] "Davao City"


#2. Create a matrix of one to eight and eleven to fourteen with four columns and three rows.

#a. What will be the R code for the #2 question and its result?

matrix(c(1:8, 11:14), ncol=4, nrow=3, )

#matrix(c(1:8, 11:14), ncol=4, nrow=3, )
#     [,1] [,2] [,3] [,4]
#[1,]    1    4    7   12
#[2,]    2    5    8   13
#[3,]    3    6   11   14

#------------------------------------------------------------------------------------------------------
#b. Multiply the matrix by two. What is its R code and its result?

2 * matrix(c(1:8, 11:14), ncol=4, nrow=3)

#2 * matrix(c(1:8, 11:14), ncol=4, nrow=3)
#     [,1] [,2] [,3] [,4]
#[1,]    2    8   14   24
#[2,]    4   10   16   26
#[3,]    6   12   22   28

#------------------------------------------------------------------------------------------------------
#c. What is the content of row 2? What is its R code?

matrix(c(1:8, 11:14), ncol=4, nrow=3)[2,]
#matrix(c(1:8, 11:14), ncol=4, nrow=3)[2,]
#[1]  2  5  8 13

#------------------------------------------------------------------------------------------------------
#d. What will be the R code if you want to display the column 3 and column 4 in row 1 and row 2? What is its output?

matrix(c(1:8, 11:14), nrow = 3, ncol = 4)[1:2, 3:4]
#matrix(c(1:8, 11:14), nrow = 3, ncol = 4)[1:2, 3:4]
#     [,1] [,2]
#[1,]    7   12
#[2,]    8   13

#------------------------------------------------------------------------------------------------------

#e. What is the R code is you want to display only the columns in 2 and 3, row 3? What is its output?
matrix(c(1:8, 11:14), nrow = 3, ncol = 4)[3, 2:3]
#[1]  6 11
#------------------------------------------------------------------------------------------------------

#f. What is the R code is you want to display only the columns 4? What is its output?
matrix(c(1:8, 11:14), nrow = 3, ncol = 4)[, 4]
#[1] 12 13 14

#------------------------------------------------------------------------------------------------------
#g. Name the rows as isa, dalawa, tatlo and columns as uno, dos, tres, quatro for the matrix that was created in b.‘. What is its R code and corresponding output?
mat <- 2* matrix(c(1:8, 11:14), nrow = 3, ncol = 4)
rownames(mat) <- c("isa", "dalawa", "tatlo")
colnames(mat) <- c("uno", "dos", "tres", "quatro")
mat

#mat <- 2* matrix(c(1:8, 11:14), nrow = 3, ncol = 4)
#rownames(mat) <- c("isa", "dalawa", "tatlo")
#colnames(mat) <- c("uno", "dos", "tres", "quatro")
#mat

#------------------------------------------------------------------------------------------------------
# h. From the original matrix you have created in a, reshape the matrix by assigning a new dimension with dim(). New dimensions should have 2 columns and 6 rows. What will be the R code and its output?
newmat <- matrix(c(1:8, 11:14), nrow = 3, ncol = 4)
dim(newmat) <- c(6, 2)
newmat
# [,1] [,2]
#[1,]    1    7
#[2,]    2    8
#[3,]    3   11
#[4,]    4   12
#[5,]    5   13
#[6,]    6   14

#------------------------------------------------------------------------------------------------------
#3. An array contains 1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1

#a.Create an array for the above numeric values. Each values will be repeated twice
#What will be the R code if you are to create a three-dimensional array with 4 columns and
#2 rows. What will be its output?

data <- c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1)

ArrayVal <- array (c (1:3, 6:9, 0, 3:5, 1), c (2,4,3))
ArrayVal
# [,1] [,2] [,3] [,4]
#[1,]    1    3    7    9
#[2,]    2    6    8    0

#, , 2

#     [,1] [,2] [,3] [,4]
#[1,]    3    5    1    3
#[2,]    4    1    2    6

#, , 3

#     [,1] [,2] [,3] [,4]
#[1,]    7    9    3    5
#[2,]    8    0    4    1

#------------------------------------------------------------------------------------------------------
#b.How many dimensions do your array have?
dim(ArrayVal)
#[1] 2 4 3

#------------------------------------------------------------------------------------------------------
#c.Name the rows as lowercase letters and columns as uppercase letters starting from
#the A. The array names should be “1st-Dimensional Array”, “2nd-Dimensional Array”, and
#“3rd-Dimensional Array”. What will be the R codes and its output?

data <- c(1:3, 6:9, 0, 3:5, 1)
ArrayVal <- array(data, dim = c(2, 4, 3))

dimnames(ArrayVal) <- list(
  c("a", "b"),
  c("A", "B", "C", "D"),
  c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array")
)

ArrayVal

#, , 1st-Dimensional Array

#  A B C D
#a 1 3 7 9
#b 2 6 8 0

#, , 2nd-Dimensional Array

#  A B C D
#a 3 5 1 3
#b 4 1 2 6

#, , 3rd-Dimensional Array

#  A B C D
#a 7 9 3 5
#b 8 0 4 1
